/**
 * GOBERNA — Analytics page layout styles
 */

export const FULL_SCREEN: React.CSSProperties = {
  display: "flex",
  flexDirection: "column",
  backgroundColor: "var(--color-surface-hover)",
  flex: 1,
  minHeight: 0,
};

export const S: Record<string, React.CSSProperties> = {
  content: {
    flex: 1,
    overflow: "auto",
    padding: 24,
    backgroundColor: "var(--color-surface-hover)",
  },
  section: { marginBottom: 24 },
  sectionLast: { marginBottom: 0 },
  sectionLabel: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    marginBottom: 16,
    marginTop: 8,
  },
  sectionLine: {
    flex: 1,
    height: 1,
    backgroundColor: "var(--color-border)",
  },
  sectionText: {
    fontSize: 11,
    fontWeight: 700,
    color: "var(--color-text-tertiary)",
    textTransform: "uppercase" as const,
    letterSpacing: "0.08em",
    whiteSpace: "nowrap" as const,
  },
  heroGrid: {
    display: "grid",
    gridTemplateColumns: "42% 1fr",
    gap: 24,
    height: 560,
    marginBottom: 24,
  },
  heroLeft: { minHeight: 0, overflow: "hidden" },
  heroRight: { minHeight: 0, overflow: "hidden" },
  grid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 24,
    marginBottom: 24,
  },
  column: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 24,
  },
  loadingContainer: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
    gap: 12,
  },
  spinner: {
    width: 32,
    height: 32,
    border: "3px solid var(--color-border)",
    borderTopColor: "#1d4ed8",
    borderRadius: "50%",
    animation: "spin 1s linear infinite",
  },
  loadingText: { fontSize: 14, color: "var(--color-text-secondary)" },
  errorContainer: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
    gap: 12,
  },
  errorTitle: { fontSize: 18, fontWeight: 600, color: "var(--color-text-primary)" },
  errorMessage: { fontSize: 14, color: "var(--color-text-secondary)" },
  backButton: {
    marginTop: 12,
    padding: "8px 20px",
    borderRadius: 8,
    border: "1px solid var(--color-border)",
    backgroundColor: "var(--color-surface)",
    color: "var(--color-text-secondary)",
    fontSize: 13,
    cursor: "pointer",
  },
  emptyContainer: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
    gap: 12,
    padding: 40,
  },
  emptyIcon: {
    width: 80,
    height: 80,
    borderRadius: "50%",
    backgroundColor: "var(--color-surface-active)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  emptyTitle: { fontSize: 18, fontWeight: 700, color: "var(--color-text-primary)" },
  emptyMessage: { fontSize: 14, color: "var(--color-text-secondary)", textAlign: "center" as const },
  emptyHint: { fontSize: 12, color: "var(--color-text-tertiary)", textAlign: "center" as const, maxWidth: 300 },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    height: 56,
    padding: "0 16px",
    backgroundColor: "var(--color-surface)",
    borderBottom: "1px solid var(--color-border)",
    flexShrink: 0,
  },
  headerLeft: { display: "flex", alignItems: "center", gap: 10 },
  headerBackBtn: {
    width: 30,
    height: 30,
    borderRadius: 8,
    border: "1px solid var(--color-border)",
    backgroundColor: "var(--color-surface-hover)",
    color: "var(--color-text-secondary)",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  headerIdentity: {},
  headerName: { fontSize: 14, fontWeight: 700, color: "var(--color-text-primary)" },
  headerMeta: { display: "flex", gap: 8, fontSize: 11, color: "var(--color-text-secondary)", alignItems: "center" },
  headerBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    padding: "2px 8px",
    borderRadius: 4,
    fontSize: 10,
    fontWeight: 700,
    textTransform: "uppercase" as const,
    color: "var(--color-text-on-primary)",
  },
};
