[webserver]
port = ":8080"

  [webserver.headers]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Methods = "GET, OPTIONS"
  Cache-Control = "public, max-age=86400, stale-while-revalidate=300"

[cache]
type = "redis"
uri = "redis://:${REDIS_PASSWORD}@redis:6379/0"
max_zoom = 20

[[providers]]
name = "neon"
type = "mvt_postgis"
uri = "${DATABASE_URL}"

  [[providers.layers]]
  name = "departamentos"
  geometry_type = "MultiPolygon"
  id_fieldname = "gid"
  sql = "SELECT gid, coddep, nomdep AS departamento, NULL::text AS capital, ST_AsMVTGeom(geom3857, !BBOX!) AS geom FROM public.peru_departamentos WHERE geom3857 && !BBOX!"

  [[providers.layers]]
  name = "provincias"
  geometry_type = "MultiPolygon"
  id_fieldname = "gid"
  sql = "SELECT gid, coddep, codprov, (coddep || codprov) AS codprov_full, nomprov AS provincia, NULL::text AS capital, ST_AsMVTGeom(geom3857, !BBOX!) AS geom FROM public.peru_provincias WHERE geom3857 && !BBOX!"

  [[providers.layers]]
  name = "distritos"
  geometry_type = "MultiPolygon"
  id_fieldname = "gid"
  sql = "SELECT gid, ubigeo, coddep, codprov, (coddep || codprov) AS codprov_full, right(ubigeo, 2) AS coddist, nomdist AS distrito, NULL::text AS capital, ST_AsMVTGeom(geom3857, !BBOX!) AS geom FROM public.peru_distritos WHERE geom3857 && !BBOX!"

[[maps]]
name = "peru"
center = [-75.0152, -9.1899, 5.0]

  [[maps.layers]]
  provider_layer = "neon.departamentos"
  min_zoom = 3
  max_zoom = 20

  [[maps.layers]]
  provider_layer = "neon.provincias"
  min_zoom = 5
  max_zoom = 20

  [[maps.layers]]
  provider_layer = "neon.distritos"
  min_zoom = 8
  max_zoom = 20
