/**
 * Dynamic Form Screen — renders fields from config.form.schema.fields.
 *
 * Maps dynamic form field values to the flat backend schema expected by POST /api/forms:
 * - nombre, telefono, fecha, x, y, zona
 * - encuestador (agent.full_name), encuestador_id (agent.id)
 * - candidato_preferido (candidate.name)
 * - client_id (device UUID)
 * - campaign_id, form_definition_id
 *
 * Special field type "location" → GPS capture with UTM conversion.
 *
 * LUGAR DE REGISTRO: Si el agente llena el campo "Lugar de registro"
 * (para datos tomados en papel y cargados luego desde casa), el GPS
 * pasa a ser opcional. Si NO se llena, el GPS sigue siendo obligatorio.
 *
 * OFFLINE-FIRST: Forms are saved to SQLite queue immediately,
 * then synced to backend when online.
 */

import { useState, useCallback, useRef, useEffect, useMemo } from 'react';
import {
  ActivityIndicator,
  Alert,
  InputAccessoryView,
  Keyboard,
  KeyboardAvoidingView,
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  View,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter, useLocalSearchParams } from 'expo-router';
import * as Location from 'expo-location';
import * as Network from 'expo-network';

import { useCandidate, useFormConfig, useAgent, useActiveCampaign } from '@/lib/app-context';
import { queueForm, forceSyncNow, phoneExistsLocally } from '@/lib/offline-queue';
import { checkPhoneDuplicate } from '@/lib/api';
import { appEvents } from '@/lib/events';
import { latLonToUtm } from '@/lib/utm';
import DistritoPicker from '@/components/DistritoPicker';
import type { FormField, UtmData, SelectedDistrito } from '@/lib/types';

// Simple UUID generator (crypto.randomUUID may not be available in RN)
function generateClientId(): string {
  const timestamp = Date.now().toString(36);
  const random = Math.random().toString(36).substring(2, 15);
  const random2 = Math.random().toString(36).substring(2, 15);
  return `${timestamp}-${random}-${random2}`;
}

const FONT = 'Montserrat-Bold';
const BORDER = '#E1E6F0';
const TEXT_MUTED = 'rgba(22, 57, 96, 0.7)';
const ERROR_RED = '#DC2626';
const AMBER = '#F59E0B';
const AMBER_BG = '#FFFBEB';

// Peru phone validation: 9 digits starting with 9
const PERU_PHONE_REGEX = /^9\d{8}$/;

// Fields that are explicitly optional (no asterisk, no validation)
const OPTIONAL_FIELDS = ['comentarios', 'observaciones', 'notas'];

// ─── Resolve form fields to backend flat schema ──────────────
// The backend expects: nombre, telefono, zona, comentarios, candidato_preferido.
// Form definitions may have arbitrary field IDs (e.g. "field_1739812345678")
// generated by the web editor. We resolve using field type + label keywords.

const NOMBRE_KEYWORDS = ['nombre', 'apellido', 'name'];
const PHONE_KEYWORDS = ['telefono', 'celular', 'phone', 'movil'];
const ZONA_KEYWORDS = ['ubicacion', 'zona', 'sector', 'distrito', 'direccion', 'barrio', 'localidad'];
const COMMENT_KEYWORDS = ['comentario', 'observacion', 'nota', 'detalle'];
const CANDIDATE_KEYWORDS = ['preferido', 'candidato', 'voto'];

function matchesKeywords(text: string, keywords: string[]): boolean {
  const normalized = text.toLowerCase().replace(/[^a-z]/g, '');
  return keywords.some((kw) => normalized.includes(kw));
}

/**
 * Given a form field, determine which backend column it maps to.
 * Priority: field.type > label keywords > id keywords > null (unknown)
 */
function resolveBackendField(field: FormField): string | null {
  const { id, type, label } = field;

  // 1. Type-based resolution (most reliable)
  if (type === 'phone') return 'telefono';
  if (type === 'location') return null; // handled separately via UTM

  // 2. Label-based resolution (works for custom field IDs)
  if (matchesKeywords(label, NOMBRE_KEYWORDS)) return 'nombre';
  if (matchesKeywords(label, PHONE_KEYWORDS)) return 'telefono';
  if (matchesKeywords(label, ZONA_KEYWORDS)) return 'zona';
  if (matchesKeywords(label, COMMENT_KEYWORDS)) return 'comentarios';
  if (matchesKeywords(label, CANDIDATE_KEYWORDS)) return 'candidato_preferido';

  // 3. ID-based resolution (fallback for well-known IDs)
  if (matchesKeywords(id, NOMBRE_KEYWORDS)) return 'nombre';
  if (matchesKeywords(id, PHONE_KEYWORDS)) return 'telefono';
  if (matchesKeywords(id, ZONA_KEYWORDS)) return 'zona';
  if (matchesKeywords(id, COMMENT_KEYWORDS)) return 'comentarios';
  if (matchesKeywords(id, CANDIDATE_KEYWORDS)) return 'candidato_preferido';

  // 4. Unknown field — will be included as-is for the backend to ignore
  return null;
}

// ─── Dynamic Field Renderer ─────────────────────────────────

// Check if a field is optional based on its ID
function isOptionalField(fieldId: string): boolean {
  const normalized = fieldId.toLowerCase().replace(/[^a-z]/g, '');
  return OPTIONAL_FIELDS.some((opt) => normalized.includes(opt));
}

// Render the required asterisk in red
function RequiredAsterisk() {
  return <Text style={styles.requiredAsterisk}>*</Text>;
}

function DynamicField({
  field,
  value,
  onChange,
  primaryColor,
  externalError,
  checkingPhone,
  gpsOpcional,
  onFocus,
  onLayout,
  inputAccessoryViewID,
  inputRef,
}: {
  field: FormField;
  value: string;
  onChange: (val: string) => void;
  primaryColor: string;
  /** Error message injected by the parent (e.g. duplicate phone) */
  externalError?: string | null;
  /** Whether a phone duplicate check is in progress */
  checkingPhone?: boolean;
  /** If true, GPS field shows as optional (lugar_registro was filled) */
  gpsOpcional?: boolean;
  /** Called when the field's text input gains focus */
  onFocus?: () => void;
  /** Capture layout for scroll-to-focused */
  onLayout?: (event: { nativeEvent: { layout: { y: number } } }) => void;
  /** InputAccessoryView ID for iOS keyboard toolbar */
  inputAccessoryViewID?: string;
  /** Ref callback for the underlying TextInput */
  inputRef?: (ref: TextInput | null) => void;
}) {
  const [capturandoGps, setCapturandoGps] = useState(false);
  const [phoneError, setPhoneError] = useState<string | null>(null);

  // Determine if this field should show required asterisk
  const isOptional = isOptionalField(field.id);
  const showRequired = field.required && !isOptional;

  // Handle phone input with validation
  const handlePhoneChange = (text: string) => {
    // Only allow digits
    const cleaned = text.replace(/\D/g, '');
    // Limit to 9 digits
    const limited = cleaned.slice(0, 9);
    onChange(limited);

    // Validate
    if (limited.length > 0 && limited.length < 9) {
      setPhoneError('Debe tener 9 digitos');
    } else if (limited.length === 9 && !limited.startsWith('9')) {
      setPhoneError('Debe empezar con 9');
    } else {
      setPhoneError(null);
    }
  };

  if (field.type === 'location') {
    const hasLocation = value !== '';
    // Si gpsOpcional=true (lugar_registro lleno), el campo GPS no muestra asterisco
    const showRequiredGps = field.required && !gpsOpcional;

    const captureLocation = async () => {
      if (capturandoGps) return;
      setCapturandoGps(true);
      try {
        // Check first — only request if not already granted.
        // Apple 5.1.1: the system dialog must come from a user action (this is a tap handler, so compliant).
        const existing = await Location.getForegroundPermissionsAsync();
        let permStatus = existing.status;
        if (permStatus !== 'granted') {
          const { status } = await Location.requestForegroundPermissionsAsync();
          permStatus = status;
        }
        if (permStatus !== 'granted') {
          Alert.alert(
            'Permiso denegado',
            'Se necesita acceso a la ubicacion para registrar coordenadas GPS.',
          );
          return;
        }
        const position = await Location.getCurrentPositionAsync({
          accuracy: Location.Accuracy.High,
        });
        const { latitude, longitude } = position.coords;
        const utm = latLonToUtm(latitude, longitude);
        onChange(JSON.stringify(utm));
      } catch (err) {
        const message = err instanceof Error ? err.message : 'Error desconocido';
        Alert.alert('Error GPS', `No se pudo obtener la ubicacion: ${message}`);
      } finally {
        setCapturandoGps(false);
      }
    };

    let displayText = capturandoGps ? 'Obteniendo GPS...' : 'Ingresar ubicacion';
    if (hasLocation) {
      try {
        const utm: UtmData = JSON.parse(value);
        displayText = `UTM ${utm.zone}${utm.hemisphere} ${Math.round(utm.easting)}E ${Math.round(utm.northing)}N`;
      } catch {
        displayText = 'Ubicacion registrada';
      }
    }

    return (
      <View style={styles.field} onLayout={onLayout}>
        <Text style={styles.label}>
          {field.label}{' '}
          {showRequiredGps ? <RequiredAsterisk /> : (
            gpsOpcional ? <Text style={styles.optionalLabel}> (opcional)</Text> : null
          )}
        </Text>
        <Pressable
          style={[
            styles.gpsBtn,
            { borderColor: primaryColor },
            hasLocation && styles.gpsBtnCaptured,
            gpsOpcional && !hasLocation && styles.gpsBtnOptional,
            capturandoGps && { opacity: 0.6 },
          ]}
          onPress={captureLocation}
          disabled={capturandoGps}
          accessibilityRole="button"
          accessibilityLabel={hasLocation ? `GPS capturado: ${displayText}` : 'Capturar ubicacion GPS'}
        >
          <Text style={[
            styles.gpsBtnText,
            { color: primaryColor },
            hasLocation && styles.gpsBtnTextCaptured,
            gpsOpcional && !hasLocation && styles.gpsBtnTextOptional,
          ]}>
            {gpsOpcional && !hasLocation ? 'Agregar GPS (opcional)' : displayText}
          </Text>
        </Pressable>
        {gpsOpcional && !hasLocation && (
          <Text style={styles.gpsOpcionalHint}>
            Omitido — usaras el lugar indicado abajo.
          </Text>
        )}
      </View>
    );
  }

  if (field.type === 'select' || field.type === 'radio') {
    return (
      <View style={styles.field} onLayout={onLayout}>
        <Text style={styles.label}>
          {field.label} {showRequired && <RequiredAsterisk />}
        </Text>
        <View style={styles.optionsContainer}>
          {(field.options ?? []).map((opt) => (
            <Pressable
              key={opt.value}
              style={[
                styles.optionBtn,
                value === opt.value && { backgroundColor: primaryColor, borderColor: primaryColor },
              ]}
              onPress={() => onChange(opt.value)}
              accessibilityRole="radio"
              accessibilityState={{ checked: value === opt.value }}
              accessibilityLabel={opt.label}
            >
              <Text
                style={[
                  styles.optionText,
                  value === opt.value && { color: '#FFFFFF' },
                ]}
              >
                {opt.label}
              </Text>
            </Pressable>
          ))}
        </View>
      </View>
    );
  }

  if (field.type === 'checkbox') {
    const checked = value === 'true';
    return (
      <View style={styles.field} onLayout={onLayout}>
        <Pressable
          style={styles.checkboxRow}
          onPress={() => onChange(checked ? 'false' : 'true')}
          accessibilityRole="checkbox"
          accessibilityState={{ checked }}
          accessibilityLabel={field.label}
        >
          <View style={[styles.checkbox, checked && { backgroundColor: primaryColor, borderColor: primaryColor }]}>
            {checked && <Text style={styles.checkmark}>✓</Text>}
          </View>
          <Text style={styles.checkboxLabel}>{field.label}</Text>
        </Pressable>
      </View>
    );
  }

  // Handle phone fields specially (by type or label/id keywords)
  const isPhoneField = field.type === 'phone' || matchesKeywords(field.label, PHONE_KEYWORDS) || matchesKeywords(field.id, PHONE_KEYWORDS);

  const keyboardType =
    field.type === 'phone' || isPhoneField
      ? 'phone-pad' as const
      : field.type === 'number'
      ? 'numeric' as const
      : field.type === 'email'
      ? 'email-address' as const
      : 'default' as const;

  const multiline = field.type === 'textarea';

  // Combined error: local format error takes priority, then external (duplicate) error
  const displayError = isPhoneField ? (phoneError ?? externalError ?? null) : null;
  const hasError = displayError !== null;

  return (
    <View style={styles.field} onLayout={onLayout}>
      <Text style={styles.label}>
        {field.label} {showRequired && <RequiredAsterisk />}
        {isOptional && <Text style={styles.optionalLabel}> (opcional)</Text>}
      </Text>
      <View>
        <TextInput
          ref={(r) => inputRef?.(r)}
          style={[
            styles.input,
            multiline && styles.inputMultiline,
            isPhoneField && hasError && styles.inputError,
          ]}
          placeholder={isPhoneField ? '987654321' : (field.placeholder ?? '')}
          placeholderTextColor={TEXT_MUTED}
          value={value}
          onChangeText={isPhoneField ? handlePhoneChange : onChange}
          onFocus={onFocus}
          keyboardType={keyboardType}
          multiline={multiline}
          numberOfLines={multiline ? 3 : 1}
          textAlignVertical={multiline ? 'top' : 'auto'}
          maxLength={isPhoneField ? 9 : field.validation?.maxLength}
          autoCapitalize={field.type === 'email' ? 'none' : 'sentences'}
          inputAccessoryViewID={inputAccessoryViewID}
        />
        {isPhoneField && checkingPhone && (
          <View style={styles.phoneCheckingIndicator}>
            <ActivityIndicator size="small" color={TEXT_MUTED} />
          </View>
        )}
      </View>
      {isPhoneField && hasError && (
        <Text style={styles.fieldError}>{displayError}</Text>
      )}
    </View>
  );
}

// ─── Screen ─────────────────────────────────────────────────

// ─── Keyboard Toolbar (iOS InputAccessoryView) ─────────────
const ACCESSORY_ID = 'goberna-form-toolbar';

function KeyboardToolbar({
  onPrev,
  onNext,
  onDone,
  hasPrev,
  hasNext,
  primaryColor,
}: {
  onPrev: () => void;
  onNext: () => void;
  onDone: () => void;
  hasPrev: boolean;
  hasNext: boolean;
  primaryColor: string;
}) {
  if (Platform.OS !== 'ios') return null;
  return (
    <InputAccessoryView nativeID={ACCESSORY_ID}>
      <View style={styles.toolbar}>
        <View style={styles.toolbarNav}>
          <Pressable
            onPress={onPrev}
            disabled={!hasPrev}
            style={[styles.toolbarBtn, !hasPrev && styles.toolbarBtnDisabled]}
            accessibilityLabel="Campo anterior"
            accessibilityRole="button"
          >
            <Text style={[styles.toolbarBtnText, !hasPrev && styles.toolbarBtnTextDisabled]}>◀</Text>
          </Pressable>
          <Pressable
            onPress={onNext}
            disabled={!hasNext}
            style={[styles.toolbarBtn, !hasNext && styles.toolbarBtnDisabled]}
            accessibilityLabel="Siguiente campo"
            accessibilityRole="button"
          >
            <Text style={[styles.toolbarBtnText, !hasNext && styles.toolbarBtnTextDisabled]}>▶</Text>
          </Pressable>
        </View>
        <Pressable
          onPress={onDone}
          style={styles.toolbarDoneBtn}
          accessibilityLabel="Cerrar teclado"
          accessibilityRole="button"
        >
          <Text style={[styles.toolbarDoneText, { color: primaryColor }]}>Listo</Text>
        </Pressable>
      </View>
    </InputAccessoryView>
  );
}

export default function NewFormScreen() {
  const router = useRouter();
  const params = useLocalSearchParams<{ prefill?: string }>();
  const candidate = useCandidate();
  const formConfig = useFormConfig();
  const agent = useAgent();
  const campaign = useActiveCampaign();

  const primary = candidate.color_primario;
  const secondary = candidate.color_secundario;

  // ── Prefill: reverse-map backend field names → form field IDs ──
  const initialFormData = useMemo(() => {
    if (!params.prefill || !formConfig) return {};
    try {
      const parsed = JSON.parse(params.prefill);
      const data: Record<string, unknown> = parsed.data ?? parsed;
      // Build reverse map: backendFieldName → formFieldId
      const reverseMap: Record<string, string> = {};
      for (const field of formConfig.schema.fields) {
        const backendKey = resolveBackendField(field);
        if (backendKey && !reverseMap[backendKey]) {
          reverseMap[backendKey] = field.id;
        }
      }
      // Populate formData using reverse map
      const result: Record<string, string> = {};
      for (const [key, value] of Object.entries(data)) {
        const fieldId = reverseMap[key];
        if (fieldId && typeof value === 'string' && value.trim()) {
          result[fieldId] = value;
        }
      }
      return result;
    } catch {
      return {};
    }
  }, [params.prefill, formConfig]);

  const [formData, setFormData] = useState<Record<string, string>>({});
  const [ubicacionUtm, setUbicacionUtm] = useState<UtmData | null>(null);
  const [lugarRegistro, setLugarRegistro] = useState<SelectedDistrito | null>(null);
  const [enviando, setEnviando] = useState(false);

  // Seed formData from prefill once formConfig is available
  useEffect(() => {
    if (Object.keys(initialFormData).length > 0) {
      setFormData(initialFormData);
    }
  }, [initialFormData]);

  // GPS es opcional cuando el agente selecciona un distrito (dato capturado en papel)
  const gpsOpcional = lugarRegistro !== null;

  // ── Scroll-to-focused-field infrastructure ───────────────────
  const scrollRef = useRef<ScrollView>(null);
  const fieldLayoutsRef = useRef<Record<string, number>>({}); // fieldId → y offset
  const inputRefsRef = useRef<Record<string, TextInput | null>>({});
  const [focusedIdx, setFocusedIdx] = useState(-1);

  // Build ordered list of text-input field IDs (for prev/next navigation)
  const textFieldIds = useMemo(() => {
    if (!formConfig) return [];
    const ids: string[] = [];
    for (const f of formConfig.schema.fields) {
      // Only fields with TextInput (text, phone, number, email, textarea)
      if (f.type !== 'location' && f.type !== 'select' && f.type !== 'radio' && f.type !== 'checkbox') {
        ids.push(f.id);
      }
    }
    return ids;
  }, [formConfig]);

  const scrollToField = useCallback((fieldId: string) => {
    const y = fieldLayoutsRef.current[fieldId];
    if (y != null && scrollRef.current) {
      // Scroll so the field is ~100px from the top (comfortable reading position above keyboard)
      scrollRef.current.scrollTo({ y: Math.max(0, y - 100), animated: true });
    }
  }, []);

  const handleFieldFocus = useCallback((fieldId: string) => {
    const idx = textFieldIds.indexOf(fieldId);
    setFocusedIdx(idx);
    // Small delay to let keyboard animate open before scrolling
    setTimeout(() => scrollToField(fieldId), 150);
  }, [textFieldIds, scrollToField]);

  const handleFieldLayout = useCallback((fieldId: string, y: number) => {
    fieldLayoutsRef.current[fieldId] = y;
  }, []);

  const focusPrev = useCallback(() => {
    if (focusedIdx <= 0) return;
    const prevId = textFieldIds[focusedIdx - 1];
    const ref = inputRefsRef.current[prevId];
    if (ref) ref.focus();
  }, [focusedIdx, textFieldIds]);

  const focusNext = useCallback(() => {
    if (focusedIdx < 0 || focusedIdx >= textFieldIds.length - 1) return;
    const nextId = textFieldIds[focusedIdx + 1];
    const ref = inputRefsRef.current[nextId];
    if (ref) ref.focus();
  }, [focusedIdx, textFieldIds]);

  const dismissKeyboard = useCallback(() => {
    Keyboard.dismiss();
    setFocusedIdx(-1);
  }, []);

  // ── Phone duplicate detection ───────────────────────────────
  const [phoneDupError, setPhoneDupError] = useState<string | null>(null);
  const [checkingPhone, setCheckingPhone] = useState(false);
  const phoneCheckTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  // Detect which field is the phone field (resolved once when formConfig changes)
  const phoneFieldId = formConfig?.schema.fields.find((f) => {
    return f.type === 'phone'
      || matchesKeywords(f.label, PHONE_KEYWORDS)
      || matchesKeywords(f.id, PHONE_KEYWORDS);
  })?.id ?? null;

  // Run duplicate check whenever the phone value reaches 9 valid digits
  useEffect(() => {
    if (!phoneFieldId || !campaign?.id) return;

    const phoneValue = (formData[phoneFieldId] ?? '').trim();

    // Clear error + cancel pending check when phone is incomplete
    if (!PERU_PHONE_REGEX.test(phoneValue)) {
      setPhoneDupError(null);
      setCheckingPhone(false);
      if (phoneCheckTimer.current) clearTimeout(phoneCheckTimer.current);
      return;
    }

    // Debounce 300ms so we don't fire on every keystroke
    if (phoneCheckTimer.current) clearTimeout(phoneCheckTimer.current);

    phoneCheckTimer.current = setTimeout(async () => {
      setCheckingPhone(true);
      setPhoneDupError(null);

      try {
        // ── Check 1: SQLite local (immediate, offline-safe) ──────
        const localDup = await phoneExistsLocally(campaign.id, phoneValue);
        if (localDup) {
          setPhoneDupError('Este número ya fue registrado');
          setCheckingPhone(false);
          return;
        }

        // ── Check 2: Backend (requires network) ─────────────────
        const networkState = await Network.getNetworkStateAsync();
        if (networkState.isConnected && networkState.isInternetReachable) {
          const result = await checkPhoneDuplicate(phoneValue);
          if (result.ok && result.data.exists) {
            setPhoneDupError('Este número ya está registrado en el servidor');
            setCheckingPhone(false);
            return;
          }
        }

        // No duplicate found
        setPhoneDupError(null);
      } catch {
        // Network error → graceful degradation, let submission pass
        setPhoneDupError(null);
      } finally {
        setCheckingPhone(false);
      }
    }, 300);

    return () => {
      if (phoneCheckTimer.current) clearTimeout(phoneCheckTimer.current);
    };
  }, [formData, phoneFieldId, campaign?.id]);

  const updateField = useCallback((fieldId: string, value: string) => {
    setFormData((prev) => ({ ...prev, [fieldId]: value }));
  }, []);

  const handleLocationCaptured = useCallback((fieldId: string, value: string) => {
    setFormData((prev) => ({ ...prev, [fieldId]: value }));
    if (value) {
      try {
        setUbicacionUtm(JSON.parse(value));
      } catch {
        // ignore
      }
    }
  }, []);

  const handleSubmit = async () => {
    if (!formConfig) return;

    const fields = formConfig.schema.fields;
    
    // Validate required fields (skip optional ones like comentarios)
    for (const field of fields) {
      const isOptional = isOptionalField(field.id);
      
      // Skip validation for optional fields
      if (isOptional) continue;

      // Skip location fields here — they have their own GPS/distrito validation below (line 646)
      if (field.type === 'location') continue;
      
      if (field.required && !formData[field.id]?.trim()) {
        Alert.alert('Campo requerido', `"${field.label}" es obligatorio.`);
        return;
      }
      
      // Phone validation for Peru (9 digits starting with 9)
      const isPhoneField = field.type === 'phone' || matchesKeywords(field.label, PHONE_KEYWORDS) || matchesKeywords(field.id, PHONE_KEYWORDS);
      if (isPhoneField && formData[field.id]) {
        const phoneValue = formData[field.id].trim();
        if (!PERU_PHONE_REGEX.test(phoneValue)) {
          Alert.alert('Telefono invalido', 'El telefono debe tener 9 digitos y empezar con 9.');
          return;
        }
        // Block submission if duplicate was detected
        if (phoneDupError) {
          Alert.alert('Número duplicado', phoneDupError);
          return;
        }
      }
      
      if (field.validation?.pattern && formData[field.id]) {
        const regex = new RegExp(field.validation.pattern);
        if (!regex.test(formData[field.id])) {
          Alert.alert('Formato invalido', `"${field.label}" no tiene el formato correcto.`);
          return;
        }
      }
      if (field.validation?.min && formData[field.id]) {
        if (formData[field.id].length < field.validation.min) {
          Alert.alert('Muy corto', `"${field.label}" debe tener al menos ${field.validation.min} caracteres.`);
          return;
        }
      }
    }

    if (!ubicacionUtm && !gpsOpcional) {
      Alert.alert(
        'Ubicacion requerida',
        'Debes capturar la ubicacion GPS, o indicar el "Lugar de registro" si cargaste el dato desde casa.',
      );
      return;
    }

    setEnviando(true);

    try {
      // Map each form field to its backend column using type + label heuristics
      const resolved: Record<string, string> = {};

      for (const field of fields) {
        if (field.type === 'location') continue; // GPS handled separately
        const value = (formData[field.id] ?? '').trim();
        if (!value) continue;

        const backendKey = resolveBackendField(field);
        if (backendKey) {
          // First match wins (in case multiple fields resolve to same key)
          if (!resolved[backendKey]) {
            resolved[backendKey] = value;
          }
        }
      }

      // Generate unique client_id
      const clientId = generateClientId();

      // Build the full payload with resolved values (no fallbacks to placeholders)
      const payloadData: Record<string, unknown> = {
        nombre: resolved.nombre || 'Sin nombre',
        telefono: resolved.telefono || '',
        fecha: new Date().toISOString(),
        candidato_preferido: resolved.candidato_preferido || candidate.name,
        encuestador: agent.full_name,
        encuestador_id: agent.id,
        comentarios: resolved.comentarios || '',
      };

      if (ubicacionUtm) {
        // GPS capturado en campo
        payloadData.x = ubicacionUtm.easting;
        payloadData.y = ubicacionUtm.northing;
        payloadData.zona = `${ubicacionUtm.zone}${ubicacionUtm.hemisphere}`;
        payloadData.lat = ubicacionUtm.latitude;
        payloadData.lng = ubicacionUtm.longitude;
      } else if (lugarRegistro) {
        // Sin GPS — dato cargado desde casa, distrito seleccionado
        // x/y/zona son NOT NULL en DB: usar 0,0 y nombre del distrito como zona
        payloadData.x = 0;
        payloadData.y = 0;
        payloadData.zona = lugarRegistro.distrito;
        payloadData.lugar_registro = `${lugarRegistro.distrito}, ${lugarRegistro.provincia}, ${lugarRegistro.departamento}`;
        payloadData.ubigeo = lugarRegistro.ubigeo;
        payloadData.departamento = lugarRegistro.departamento;
        payloadData.provincia = lugarRegistro.provincia;
        payloadData.distrito = lugarRegistro.distrito;
        payloadData.coord_source = 'distrito_picker';
      }

      // OFFLINE-FIRST: Queue the form locally first
      await queueForm({
        client_id: clientId,
        campaign_id: campaign.id,
        form_definition_id: formConfig.id,
        data: payloadData,
      });

      // Notify dashboard immediately so the table updates
      appEvents.emit('forms:changed');

      // Try to sync immediately in background (non-blocking)
      forceSyncNow().catch(() => {
        // Ignore sync errors - data is safe in SQLite
      });

      // Reset form for next entry
      setFormData({});
      setUbicacionUtm(null);
      setLugarRegistro(null);

      // Success - form is saved locally and will sync when online
      Alert.alert(
        'Guardado',
        'Registro guardado. Se sincronizara automaticamente cuando haya conexion.',
        [{ text: 'OK', onPress: () => router.back() }]
      );
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Error desconocido';
      Alert.alert('Error', `No se pudo guardar el formulario: ${message}`);
    } finally {
      setEnviando(false);
    }
  };

  // No form defined
  if (!formConfig) {
    return (
      <SafeAreaView style={styles.safeArea}>
        <View style={styles.noFormContainer}>
          <Text style={styles.noFormTitle}>Sin formulario</Text>
          <Text style={styles.noFormText}>
            No hay un formulario activo para esta campana.
          </Text>
          <Pressable
            style={[styles.backBtn, { backgroundColor: primary }]}
            onPress={() => router.back()}
          >
            <Text style={styles.backBtnText}>Volver</Text>
          </Pressable>
        </View>
      </SafeAreaView>
    );
  }

  const fields = formConfig.schema.fields;

  return (
    <SafeAreaView style={styles.safeArea}>
      <KeyboardAvoidingView
        style={styles.flex}
        behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
        keyboardVerticalOffset={Platform.OS === 'ios' ? 0 : 24}
      >
        <ScrollView
          ref={scrollRef}
          contentContainerStyle={styles.scroll}
          keyboardShouldPersistTaps="handled"
          keyboardDismissMode="interactive"
          showsVerticalScrollIndicator={false}
        >
          <View style={styles.header}>
            <Pressable
              onPress={() => router.back()}
              style={styles.backBtnSimple}
              accessibilityRole="button"
              accessibilityLabel="Volver a la pantalla anterior"
            >
              <Text style={[styles.backText, { color: TEXT_MUTED }]}>← Volver</Text>
            </Pressable>
            <Text style={[styles.title, { color: primary }]} accessibilityRole="header">
              {formConfig.name}
            </Text>
            <Text style={[styles.subtitle, { color: TEXT_MUTED }]}>Agente: {agent.full_name}</Text>
          </View>

          <View style={styles.form}>
            {fields.map((field) => (
              <DynamicField
                key={field.id}
                field={field}
                value={formData[field.id] ?? ''}
                onChange={
                  field.type === 'location'
                    ? (val) => handleLocationCaptured(field.id, val)
                    : (val) => updateField(field.id, val)
                }
                primaryColor={primary}
                externalError={field.id === phoneFieldId ? phoneDupError : null}
                checkingPhone={field.id === phoneFieldId ? checkingPhone : false}
                gpsOpcional={field.type === 'location' ? gpsOpcional : undefined}
                onFocus={() => handleFieldFocus(field.id)}
                onLayout={(e) => handleFieldLayout(field.id, e.nativeEvent.layout.y)}
                inputAccessoryViewID={ACCESSORY_ID}
                inputRef={(r) => { inputRefsRef.current[field.id] = r; }}
              />
            ))}

            <View style={[styles.candidatoCard, { backgroundColor: primary }]}>
              <Text style={styles.candidatoLabel}>Candidato</Text>
              <Text style={styles.candidatoName}>{candidate.name}</Text>
              <Text style={[styles.candidatoDetail, { color: secondary }]}>
                {candidate.cargo} · {candidate.partido}
              </Text>
            </View>

            {/* ── Lugar de registro (hace GPS opcional) ─────────── */}
            <View
              style={styles.lugarRegistroCard}
              onLayout={(e) => handleFieldLayout('__lugar_registro__', e.nativeEvent.layout.y)}
            >
              <Text style={styles.lugarRegistroTitle}>
                ¿Dato tomado en papel?
              </Text>
              <Text style={styles.lugarRegistroDesc}>
                Si cargaste este registro desde casa, selecciona el distrito
                donde recogiste el dato. Esto reemplaza la ubicacion GPS.
              </Text>
              <DistritoPicker
                value={lugarRegistro}
                onSelect={setLugarRegistro}
                onClear={() => setLugarRegistro(null)}
                primaryColor={primary}
                placeholder="Seleccionar distrito..."
              />
              {lugarRegistro && (
                <Text style={styles.lugarRegistroHint}>
                  GPS omitido — registrado en {lugarRegistro.distrito}, {lugarRegistro.provincia}.
                </Text>
              )}
            </View>
          </View>

          <Pressable
            style={[styles.saveBtn, { backgroundColor: secondary }, (enviando || !!phoneDupError || checkingPhone) && styles.saveBtnDisabled]}
            onPress={() => { dismissKeyboard(); handleSubmit(); }}
            disabled={enviando || !!phoneDupError || checkingPhone}
            accessibilityRole="button"
            accessibilityLabel={enviando ? 'Enviando registro' : 'Enviar registro'}
          >
            <Text style={[styles.saveBtnText, { color: primary }]}>
              {enviando ? 'Enviando...' : checkingPhone ? 'Verificando...' : 'Enviar registro'}
            </Text>
          </Pressable>

          {/* Extra space at bottom so last field isn't stuck against the keyboard */}
          <View style={styles.keyboardSpacer} />
        </ScrollView>
      </KeyboardAvoidingView>

      {/* iOS keyboard toolbar with Prev / Next / Done */}
      <KeyboardToolbar
        onPrev={focusPrev}
        onNext={focusNext}
        onDone={dismissKeyboard}
        hasPrev={focusedIdx > 0}
        hasNext={focusedIdx >= 0 && focusedIdx < textFieldIds.length - 1}
        primaryColor={primary}
      />
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#FFFFFF' },
  flex: { flex: 1 },
  scroll: { padding: 20, paddingBottom: 40 },
  header: { marginBottom: 24 },
  backBtnSimple: { marginBottom: 12, paddingVertical: 8 },
  backText: { fontSize: 15, fontFamily: FONT },
  title: { fontSize: 24, fontFamily: FONT },
  subtitle: { fontSize: 14, fontFamily: FONT, marginTop: 4 },
  form: { gap: 22 },
  field: { gap: 8 },
  label: {
    fontSize: 14,
    color: '#163960',
    fontFamily: FONT,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  requiredAsterisk: {
    color: ERROR_RED,
    fontSize: 15,
    fontWeight: '700',
  },
  optionalLabel: {
    fontSize: 11,
    color: TEXT_MUTED,
    textTransform: 'lowercase',
    fontFamily: FONT,
  },
  input: {
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 12,
    padding: 16,
    fontSize: 17,
    color: '#163960',
    fontFamily: FONT,
    backgroundColor: '#F8FAFC',
    // Minimum 48dp touch target (Android Material guideline)
    minHeight: 52,
  },
  inputMultiline: { minHeight: 90, paddingTop: 14 },
  inputError: { borderColor: ERROR_RED, backgroundColor: '#FEF2F2' },
  fieldError: {
    fontSize: 12,
    color: ERROR_RED,
    fontFamily: FONT,
    marginTop: 4,
  },
  phoneCheckingIndicator: {
    position: 'absolute',
    right: 14,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
  },
  gpsBtn: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 16,
    minHeight: 52,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F8FAFC',
  },
  gpsBtnCaptured: { backgroundColor: '#DCFCE7', borderColor: '#22C55E' },
  gpsBtnOptional: { borderStyle: 'dashed', backgroundColor: AMBER_BG, borderColor: AMBER },
  gpsBtnText: { fontSize: 15, fontFamily: FONT },
  gpsBtnTextCaptured: { color: '#22C55E' },
  gpsBtnTextOptional: { color: AMBER },
  gpsOpcionalHint: { fontSize: 12, color: AMBER, fontFamily: FONT },
  optionsContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  optionBtn: {
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 16,
    minHeight: 48,
    justifyContent: 'center',
    backgroundColor: '#F8FAFC',
  },
  optionText: { fontSize: 15, color: '#163960', fontFamily: FONT },
  checkboxRow: { flexDirection: 'row', alignItems: 'center', gap: 12, minHeight: 48 },
  checkbox: {
    width: 28,
    height: 28,
    borderRadius: 7,
    borderWidth: 2,
    borderColor: BORDER,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkmark: { color: '#FFFFFF', fontSize: 16, fontFamily: FONT },
  checkboxLabel: { fontSize: 16, color: '#163960', fontFamily: FONT, flex: 1 },
  candidatoCard: { borderRadius: 16, padding: 16, gap: 4 },
  candidatoLabel: {
    fontSize: 11,
    color: 'rgba(255, 255, 255, 0.6)',
    fontFamily: FONT,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  candidatoName: { fontSize: 18, color: '#FFFFFF', fontFamily: FONT },
  candidatoDetail: { fontSize: 13, fontFamily: FONT },
  saveBtn: { borderRadius: 14, padding: 18, alignItems: 'center', marginTop: 32, minHeight: 56 },
  saveBtnDisabled: { opacity: 0.6 },
  saveBtnText: { fontSize: 17, fontFamily: FONT, textTransform: 'uppercase', letterSpacing: 1 },
  noFormContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 32, gap: 16 },
  noFormTitle: { fontSize: 22, color: '#163960', fontFamily: FONT },
  noFormText: { fontSize: 15, color: TEXT_MUTED, fontFamily: FONT, textAlign: 'center' },
  backBtn: { borderRadius: 14, paddingVertical: 14, paddingHorizontal: 32, minHeight: 48 },
  backBtnText: { fontSize: 14, color: '#FFFFFF', fontFamily: FONT, textTransform: 'uppercase' },
  // Lugar de registro
  lugarRegistroCard: {
    borderWidth: 1.5,
    borderColor: AMBER,
    borderRadius: 14,
    padding: 16,
    backgroundColor: AMBER_BG,
    gap: 10,
  },
  lugarRegistroTitle: {
    fontSize: 14,
    color: '#92400E',
    fontFamily: FONT,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  lugarRegistroDesc: {
    fontSize: 13,
    color: '#78350F',
    fontFamily: FONT,
    lineHeight: 20,
  },
  lugarRegistroHint: {
    fontSize: 12,
    color: '#059669',
    fontFamily: FONT,
  },
  // Keyboard spacer — extra room so last field isn't crushed against keyboard
  keyboardSpacer: { height: 120 },
  // iOS keyboard toolbar
  toolbar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#F2F2F7',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(60,60,67,.18)',
  },
  toolbarNav: { flexDirection: 'row', gap: 6 },
  toolbarBtn: {
    width: 44,
    height: 38,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(60,60,67,.18)',
  },
  toolbarBtnDisabled: { opacity: 0.35 },
  toolbarBtnText: { fontSize: 16, color: '#163960', fontWeight: '600' },
  toolbarBtnTextDisabled: { color: TEXT_MUTED },
  toolbarDoneBtn: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  toolbarDoneText: {
    fontSize: 16,
    fontWeight: '700',
    fontFamily: FONT,
  },
});
