import { z } from "zod";

export const formSchema = z.object({
  client_id: z.string().trim().min(1).optional(),
  campaign_id: z.string().uuid().optional(),
  form_definition_id: z.string().uuid().optional(),
  encuesta_id: z.string().trim().optional(),
  nombre: z.string().trim().optional(),
  telefono: z.string().trim().optional(),
  fecha: z.string().datetime().optional(),
  x: z.coerce.number().optional(),
  y: z.coerce.number().optional(),
  zona: z.string().trim().optional(),
  candidate: z.string().trim().optional(),
  candidato_preferido: z.string().trim().optional(),
  encuesta: z.string().trim().optional(),
  observaciones: z.string().trim().optional(),
  comentarios: z.string().trim().optional(),
  hogar: z.record(z.unknown()).optional(),
  respondio: z.string().trim().optional(),
  respuesta: z.string().trim().optional(),
  hogar_id: z.string().trim().optional(),
  hogar_tipo: z.string().trim().optional(),
  hogar_nombre: z.string().trim().optional(),
  hogar_direccion: z.string().trim().optional(),
  hogar_referencia: z.string().trim().optional(),
  hogar_integrantes: z.number().optional(),
  hogar_jefe: z.record(z.unknown()).optional(),
  ubicacion: z.record(z.unknown()).optional(),
  ubicacion_gps: z.record(z.unknown()).optional(),
  lat: z.number().optional(),
  lng: z.number().optional(),
  accuracy: z.number().optional(),
  altitud: z.number().optional(),
  heading: z.number().optional(),
  speed: z.number().optional(),
  battery: z.number().optional(),
  timestamp: z.number().optional(),
  agente: z.string().trim().optional(),
  agente_id: z.string().trim().optional(),
  agente_nombre: z.string().trim().optional(),
  agente_telefono: z.string().trim().optional(),
  usuario: z.string().trim().optional(),
  usuario_id: z.string().trim().optional(),
  submitted_at: z.string().datetime().optional(),
  synced_at: z.string().datetime().optional(),
  encuestas: z.record(z.unknown()).optional(),
  home_maps_url: z.string().trim().optional(),
  polling_place_url: z.string().trim().optional(),
  encuesta_status: z.string().trim().optional(),
  respuesta_multiple: z.record(z.unknown()).optional(),
  image_url: z.string().trim().optional(),
  image_urls: z.array(z.string()).optional(),
  created_at: z.string().datetime().optional(),
  updated_at: z.string().datetime().optional(),
}).passthrough();

export type FormInput = z.infer<typeof formSchema>;
